version: 2.1

orbs:
  node: circleci/node@4.1


jobs:
  build:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      # If you are using yarn instead npm, remove the line above and uncomment the two lines below.
      # - node/install-packages:
      #     pkg-manager: yarn 
      - run:
          name: Execute build
          command: npm build

workflows:
  sample: 
    jobs:
      - build
